In [1]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])


1


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])


2


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])


7


In [11]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('2nd element on 1st row:', arr[0, 1])


2nd element on 1st row: 2


In [12]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print('5nd element on 2st row:', arr[1, 4])


5nd element on 2st row: 10


In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


[1 2 3 4]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


[1 3 5 7]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)


[1 2 3 4]
int32


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 31

print(arr)
print(x)


[31  2  3  4  5]
[1 2 3 4 5]


In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [24]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)


1
2
3


In [26]:
import numpy as np

arr = np.array([[1, 2, 3],[4,5,6]])

for x in arr:
    print(x)


[1 2 3]
[4 5 6]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)


(array([3, 5, 6], dtype=int64),)


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr % 2 == 0)
print(x)


(array([1, 3, 5, 7], dtype=int64),)


In [32]:
import numpy as np

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)


1


In [33]:
import numpy as np

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)


[1 2 3]


In [34]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


[0 1 2 3]


In [35]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))


['apple' 'banana' 'cherry']


In [36]:
import numpy as np

arr = np.array([True, False, True])
print(np.sort(arr))


[False  True  True]
